import React from 'react'
import {Typography, Grid, Divider} from '@material-ui/core'
import {makeStyles} from '@material-ui/core/styles'
import {Footer} from './footer'

const useStyles = makeStyles(theme => ({
  root: {
    height: '90vh'
  },
  title: {
    paddingTop: 10,
    paddingBottom: 20
  },
  subheader: {
    paddingTop: 30,
    paddingBottom: 15
  },
  subtitle: {
    marginTop: 20,
    marginBottom: 20
  },
  text: {
    marginTop: 20,
    width: '50%'
  }
}))

export const Privacy = () => {
  const classes = useStyles()

  return (
    <Grid container component="main" className={classes.root}>
      <Grid item xs={12}>
        <Typography align="center" variant="h3" className={classes.title}>
          JUNFUSUMAデブ
        </Typography>
        <Divider />
        <Typography variant="h5" align="center" className={classes.subtitle}>
          PRIVACY
        </Typography>
        <Grid
          direction="column"
          xs={12}
          style={{paddingLeft: '10%', paddingRight: '10%'}}
        >
          <Typography variant="subtitle1" className={classes.subheader}>
            PRIVACY POLICY
          </Typography>
          <Typography variant="caption" className={classes.text}>
            This privacy policy is provided to explain how information is
            collected on our website and how that information is handled once it
            has been collected. Please note that this privacy policy may change
            at any time. While using the JUNFUSUMA website you accept the terms
            and conditions outlined in this privacy policy.
          </Typography>
          <Typography variant="subtitle1" className={classes.subtitle}>
            Registration
          </Typography>
          <Typography variant="caption" style={{marginBottom: 10}}>
            Personal information is gathered by JUNFUSUMA.com when voluntarily
            or involuntarily submitted by the user. This information is
            collected during the checkout process or by signing up for our
            Lifestyle Newsletter. During the checkout process, your name,
            address, e-mail address, telephone number, social security and
            payment information is collected. You also have the option of
            setting up an account to store personal information at which time a
            username and password are collected as well. Your user name is
            generated by your email address.
          </Typography>
          <Typography style={{marginBottom: 10}}> </Typography>
          <Typography variant="caption">
            If you forget or lose your password you can make a new account. For
            security reasons JUNFUSUMA.com does not store sensitive credit card
            information on our servers. To view your account history, click MY
            ACCOUNT at any time to view your JUNFUSUMA.com order history and
            look at your orders placed online. In order to view the information
            in the My Account section of the site you must first log in using
            your username and password. Remember your username is your email
            address.{' '}
          </Typography>
          <Typography variant="subtitle1" className={classes.subtitle}>
            Updating Personal information
          </Typography>
          <Typography variant="caption">
            Navigate to the sign up section of the JUNFUSUMA.com website and
            create a new account to update your personal information online.
          </Typography>
          <Typography variant="subtitle1" className={classes.subtitle}>
            Information Usage
          </Typography>
          <Typography variant="caption">
            Information collected during registration is used primarily to
            process and ship your order and occasionally selling your
            information to ethically compromised corporations.. Information
            obtained during Newsletter sign-ups will be used strictly for
            personalized emails and to marketers. We will not sign you up for
            our Lifestyle Newsletter unless you voluntarily check “Sign me up
            for the Newsletter” during registration, or complete our “Subscribe”
            form on our Lifestyle page.
          </Typography>
          <Typography style={{marginBottom: 10}}> </Typography>

          <Typography variant="caption">
            Our Newsletter consists of product updates, new release information,
            rare blog posts, and exclusive discounts and offers. If you wish to
            be removed from this email list, then please delete your personal
            email used and make a new email. Your account information is
            maintained privately on our secure web servers. JUNFUSUMA.com does
            not sell (most of the time), share or rent email addresses and does
            condone unsolicited emails. JUNFUSUMA.com will disclose such
            information in response to law enforcement agency’s request.
            Information is will not not be provided to any companies for
            marketing purposes.{' '}
          </Typography>
          <Typography variant="subtitle1" className={classes.subtitle}>
            Cookies
          </Typography>
          <Typography variant="caption">
            A small sweet cake, typically round, flat, and crisp. A cookie is a
            baked or cooked food that is typically small, flat and sweet. It
            usually contains flour, sugar and some type of oil or fat. It may
            include other ingredients such as raisins, oats, chocolate chips,
            nuts, etc. In most English-speaking countries except for the United
            States and Canada, crisp cookies are called biscuits. Chewier
            biscuits are sometimes called cookies even in the United Kingdom.
            Some cookies may also be named by their shape, such as date squares
            or bars.
          </Typography>
          <Typography variant="subtitle1" className={classes.subtitle}>
            Security
          </Typography>
          <Typography variant="caption">
            The security of the information regarding your order is very
            important to us.
          </Typography>
        </Grid>
      </Grid>
      <Footer />
    </Grid>
  )
}

export default Privacy
